CREATE TABLE FLAGS (
  ID VARCHAR(255) NOT NULL,
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
) ENGINE = INNODB DEFAULT CHARSET utf8;

INSERT INTO FLAGS(ID, NAME) VALUES('0','Money Laundering');
INSERT INTO FLAGS(ID, NAME) VALUES('1','Suspicious EFT/Wire Transfers');
INSERT INTO FLAGS(ID, NAME) VALUES('2','Multiple Identities');
INSERT INTO FLAGS(ID, NAME) VALUES('3','Money Laundering');

